# Homework 2 Yuankai Wang

In [114]:
import numpy as np
import pandas as pd

# Question 1

In [115]:
# Predict M.flatten() = [1,2,3,4,5,6]

In [116]:
M = np.array([[1,2,3],[4,5,6]])
M.flatten()

array([1, 2, 3, 4, 5, 6])

# Question 2

In [117]:
def RMSE(y, yh):
    dy = yh - y
    dy2 = dy * dy
    rmse = np.sqrt(dy2.mean())
    return rmse

In [118]:
def calculate(X, y):
    A = np.matmul(X.T, X)
    b = np.matmul(X.T, y)
    wopt = np.linalg.solve(A,b)
    return wopt

In [119]:
x = np.array([-1,0,2])

In [120]:
y = np.array([2,1,5])
y

array([2, 1, 5])

# a

In [121]:
# I
# 2=c0-c1, 1=c0, 5=c0+2*c1
X = np.array([[1,-1],[1,0],[1,2]])
X

array([[ 1, -1],
       [ 1,  0],
       [ 1,  2]])

In [122]:
# II
# More equations than unknowns

In [123]:
# III
a = calculate(X,y)
a

array([2.28571429, 1.14285714])

In [124]:
# y = 2.28571429 + 1.14285714 * x

In [125]:
# IV
yh = a[0] + a[1]*x
rmse = RMSE(y, yh)
rmse

0.9258200997725515

# b

In [126]:
# I
# 2=c0-c1+c2, 1=c0, 5=c0+2*c1+4*c2
X = np.array([[1,-1,1],[1,0,0],[1,2,4]])
X

array([[ 1, -1,  1],
       [ 1,  0,  0],
       [ 1,  2,  4]])

In [127]:
# II
# The same number of equations as unknowns

In [128]:
# III
a = calculate(X,y)
a

array([ 1.0000000e+00, -4.4408921e-16,  1.0000000e+00])

In [129]:
# y = 1.0000000e+00 - 4.4408921e-16 * x + 1.0000000e+00 * x^2

In [130]:
# IV
yh = a[0] + a[1]*x + a[2]*(x**2)
rmse = RMSE(y, yh)
rmse

5.127900497022837e-16

# c

In [131]:
# I
# 2=c0-c1+c2-c3, 1=c0, 5=c0+2*c1+4*c2+8*c3
X = np.array([[1,-1,1,-1],[1,0,0,0],[1,2,4,8]])
X

array([[ 1, -1,  1, -1],
       [ 1,  0,  0,  0],
       [ 1,  2,  4,  8]])

In [132]:
# II
# Fewer equations than unknowns

In [133]:
# III
a = calculate(X,y)
a

array([ 1.        ,  2.52941176,  2.26470588, -1.26470588])

In [134]:
# y = 1. + 2.52941176 * x + 2.26470588 * x^2 - 1.26470588 * x^3

In [135]:
# IV
yh = a[0] + a[1]*x + a[2]*(x**2) + a[3]*(x**3)
rmse = RMSE(y, yh)
rmse

1.2625990704234373e-15

# Question 3

In [136]:
df = pd.read_csv("wine_quality_white.csv",sep=';')

In [137]:
features = df.drop('quality',axis=1)
features['bias'] = 1
target = df['quality']
X = features.values
y = target.values

In [138]:
A = np.matmul(X.T, X)
b = np.matmul(X.T, y)
wopt = np.linalg.solve(A,b)
pd.Series(wopt,index=features.columns)

fixed acidity             0.065520
volatile acidity         -1.863177
citric acid               0.022090
residual sugar            0.081483
chlorides                -0.247277
free sulfur dioxide       0.003733
total sulfur dioxide     -0.000286
density                -150.284181
pH                        0.686344
sulphates                 0.631476
alcohol                   0.193476
bias                    150.192842
dtype: float64

In [139]:
yh = np.matmul(X, wopt)
RMSE(y, yh)

0.7504359153109992

In [140]:
y.std()

0.8855481621683543