In [1]:
import numpy as np

In [2]:
BATCH_SIZE = 6
EPOCHS = 2
N = 40

In [3]:
np.random.seed(0)

In [4]:
minibatch_size = np.ceil(N/BATCH_SIZE-1)

In [5]:
minibatch_size

6.0

In [6]:
rand = np.random.permutation(N)

In [7]:
i = 0

In [8]:
temp_rand = rand.tolist()

In [9]:
while(rand.size % minibatch_size > 0):
    rand = np.append(rand, rand[i])
    i = i + 1

In [10]:
np.array_split(rand,7)

[array([22, 20, 25,  4, 10, 15]),
 array([28, 11, 18, 29, 27, 35]),
 array([37,  2, 39, 30, 34, 16]),
 array([36,  8, 13,  5, 17, 14]),
 array([33,  7, 32,  1, 26, 12]),
 array([31, 24,  6, 23, 21, 19]),
 array([ 9, 38,  3,  0, 22, 20])]