# Lesson  (Tensors and Convolution)

http://cs231n.github.io/convolutional-networks/

In [1]:
import numpy as np

X = np.zeros((7,7,3))

W = np.zeros((2,3,3,3))

X[:,:,0] = np.array([
        [0,0,0,0,0,0,0],
        [0,0,0,1,1,0,0],
        [0,0,2,0,1,1,0],
        [0,0,0,2,1,1,0],
        [0,2,1,0,0,1,0],
        [0,1,1,2,1,0,0],
        [0,0,0,0,0,0,0]
    ])
X[:,:,1] = np.array([
        [0,0,0,0,0,0,0],
        [0,2,2,0,1,2,0],
        [0,0,0,2,2,1,0],
        [0,1,2,0,2,0,0],
        [0,0,2,0,0,2,0],
        [0,2,1,0,2,1,0],
        [0,0,0,0,0,0,0]
    ])
X[:,:,2] = np.array([
        [0,0,0,0,0,0,0],
        [0,0,1,0,2,1,0],
        [0,2,1,1,2,0,0],
        [0,0,2,1,1,0,0],
        [0,0,2,2,0,0,0],
        [0,2,0,0,2,0,0],
        [0,0,0,0,0,0,0]
    ])
W[0,:,:,0] = np.array([
        [1,1,0],
        [0,-1,-1],
        [0,1,-1],
    ])
W[0,:,:,1] = np.array([
        [1,0,0],
        [0,0,-1],
        [-1,1,0],
    ])
W[0,:,:,2] = np.array([
        [0,-1,0],
        [-1,1,1],
        [1,1,0],
    ])
W[1,:,:,0] = np.array([
        [-1,-1,0],
        [1,0,0],
        [-1,1,1],
    ])
W[1,:,:,1] = np.array([
        [0,-1,0],
        [1,-1,0],
        [-1,0,1],
    ])
W[1,:,:,2] = np.array([
        [0,-1,1],
        [-1,1,1],
        [1,0,0],
    ])
b = np.array([1,0])

In [2]:
Y = np.zeros((3,3,2))

# < code removed >

for l in range(2):
    print(Y[:,:,l])
    print()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [4]:
for i in range(2):
    for j in range(2):
        for k in range(1):
            temp = np.matmul(X[i*2:(i+1)*2,j*2:(j+1)*2,:],W[k,:,:,:])
            Y[i,j,k] = temp

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2,3)->(2,2,newaxis,3) (3,3,3)->(3,newaxis,3,3) 