In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# inputs and corresponding outputs (targets)
x = np.array([67,67,72,69,69,70,67,67,66,68])
y = np.array([128,123,129,143,132,142,112,118,108,119])

In [4]:
#def MSE loss funciton
def MSE(w,b,x,y):
    n = len(x)
    yh = w * x + b
    dy = y - yh
    dy2 = dy * dy
    return dy2.mean()

In [6]:
X = np.ones((10,2))
X[:,0] = x
print(X)

[[67.  1.]
 [67.  1.]
 [72.  1.]
 [69.  1.]
 [69.  1.]
 [70.  1.]
 [67.  1.]
 [67.  1.]
 [66.  1.]
 [68.  1.]]


In [7]:
A = np.matmul(X.T, X)
A

array([[4.6542e+04, 6.8200e+02],
       [6.8200e+02, 1.0000e+01]])

In [8]:
b = np.matmul(X.T, y)
b

array([85650.,  1254.])

In [9]:
wopt = np.linalg.solve(A,b)
wopt

array([   4.2972973 , -167.67567568])

In [11]:
yh = np.matmul(X,wopt)
dy = yh - y
dy2 = dy * dy
rmse = np.sqrt(dy2.mean())
print('RMSE = ',rmse)

RMSE =  8.281206335937918


In [12]:
y.std()

11.101351269102334